from django.urls import path
from . import views

urlpatterns = [
    path('', views.index, name='index'),
    path('products/', views.products, name='products'),
    path('services/', views.services, name='services'),
    path('about/', views.about, name='about'),
    path('contact/', views.contact, name='contact'),
    path('products/vacuums/', views.vacuums, name='vacuums'),
    path('products/scrubbers/', views.scrubbers, name='scrubbers'),
    path('products/sweepers/', views.sweepers, name='sweepers'),
    path('products/polishers/', views.polishers, name='polishers'),
    path('products/carpet-accessories/', views.carpet_accessories, name='carpet accessories'),
    path('products/foggers/', views.foggers, name='foggers'),
    path('products/vacuums/w36', views.w36, name='w36'),
    path('products/vacuums/w86', views.w86, name='w86'),
    path('products/vacuums/v20', views.v20, name='v20'),
    path('products/scrubbers/i15b', views.i15b, name='i15b'),
    path('products/scrubbers/i35b', views.i35b, name='i35b'),
    path('products/scrubbers/i50b', views.i50b, name='i50b'),
    path('products/scrubbers/i50bt', views.i50bt, name='i50bt'),
    path('products/scrubbers/i70bt', views.i70bt, name='i70bt'),
    path('products/scrubbers/gm50b', views.gm50b, name='gm50b'),
    path('products/scrubbers/gm56bt', views.gm56bt, name='gm56bt'),
    path('products/scrubbers/gm70bt', views.gm70bt, name='gm70bt'),
    path('products/scrubbers/gm65rbt', views.gm65rbt, name='gm65rbt'),
    path('products/scrubbers/gm110', views.gm110, name='gm110'),
    path('products/scrubbers/i130', views.i130, name='i130'),
    path('products/scrubbers/gm130', views.gm130, name='gm130'),
    path('products/scrubbers/gm160', views.gm160, name='gm160'),
    path('products/scrubbers/gm230', views.gm230, name='gm230'),
    path('products/sweepers/s1500d', views.s1500d, name='s1500d'),
    path('products/sweepers/s1900d', views.s1900d, name='s1900d'),
    path('products/sweepers/isweep', views.isweep, name='isweep'),
    path('products/polishers/fc1517', views.fc1517, name='fc1517'),
    path('products/polishers/fc2517', views.fc2517, name='fc2517'),
    path('products/carpet-accessories/c1', views.c1, name='c1'),
    path('products/carpet-accessories/c2', views.c2, name='c2'),
    path('products/carpet-accessories/b3', views.b3, name='b3'),
    path('products/foggers/x5', views.x5, name='x5'),
]