# Generated by Django 4.2.2 on 2023-06-13 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cewa_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_admin',
            field=models.BooleanField(default=False),
        ),
    ]
